### ISSUE TITLE
Need root for `pip install idesolver`

### ISSUE THREAD

**Issue by iljah** [JoshKarpel/idesolver#3]
I would be nice to mention in readme that the given pip command requires root and/or also provide a version for local installation: `pip install --user idesolver`

**Comment by JoshKarpel** [comment]
I suspect you're trying to install into the system Python. If you install into a virtual environment, you shouldn't need `sudo` or `--user`. Virtual environment installation is the standard - I've added a note to this effect in the readme and the quickstart.

**Comment by JoshKarpel** [comment]
@iljah - could you clarify whether the above comment fixed the issue so that I can close?

**Comment by iljah** [comment]
Virtual environment also works but in that case it would be helpful to show all required commands, which I guess could be:
```
python3 -m venv $HOME/idesolver-env
pip install idesolver
```
assuming the user already has pip installed, etc.

**Comment by JoshKarpel** [comment]
I'd prefer not to explicitly write out the instructions, instead linking to some external resource (which was done in https://github.com/JoshKarpel/idesolver/commit/7ebb514ce1f958d8ef9cf8f23c5830ffb5953dfc). Although installing into virtual environments is the standard, the preferred method of doing that is changing pretty fast these days (I use conda, for example, and pipenv is becoming popular recently). I like the current solution of linking to the official docs on virtual environments, since it's the common denominator where any virtual environment solution starts from. The instructions for any particular solution are going to be quite different from each other, and any specifics given may conflict with whatever the user already has installed.
